name: Build Custom Kernel - Proton Clang

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Kernel Source
        uses: actions/checkout@v4
        with:
          repository: nevadamurdock/generic_kernel_mediatek_alps
          path: kernel

      - name: Setup Build Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential flex bison libssl-dev libelf-dev libarchive-tools

      - name: Download Proton Clang
        run: |
          # Clone prebuilt binary (depth 1 agar cepat)
          git clone https://github.com/kdrag0n/proton-clang.git --depth=1 toolchain

      - name: Build Kernel
        run: |
          cd kernel
          
          # Setup Toolchain Path
          TC_DIR="${GITHUB_WORKSPACE}/toolchain"
          export PATH="$TC_DIR/bin:$PATH"
          
          # Variabel Konfigurasi
          ARCH=arm64
          DEFCONFIG=k65v1_64_bsp_defconfig # GANTI dengan nama file defconfig Anda
          
          # Bersihkan direktori build
          mkdir out
          
          # Langkah 1: Generate Config
          make O=out ARCH=$ARCH $DEFCONFIG
          
          # Langkah 2: Proses Build
          # Proton Clang mendukung penggunaan LLVM=1 secara penuh untuk LTO
          make -j$(nproc --all) O=out \
              ARCH=$ARCH \
              CC=clang \
              CROSS_COMPILE=aarch64-linux-gnu- \
              CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
              LLVM=1 \
              LLVM_IAS=1 \
              LD=ld.lld \
              AR=llvm-ar \
              NM=llvm-nm \
              OBJCOPY=llvm-objcopy \
              OBJDUMP=llvm-objdump \
              STRIP=llvm-strip

      - name: Check Results
        run: |
          if [ -f kernel/out/arch/arm64/boot/Image ]; then
             echo "Kernel build successfully!"
          else
             echo "Kernel image not found!"
             exit 1
          fi

      - name: Upload Kernel Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-Proton-LTO
          path: |
            kernel/out/arch/arm64/boot/Image*
            kernel/out/arch/arm64/boot/dtbo.img
